name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies  
        run: pnpm install

      - uses: nrwl/nx-set-shas@v4

      - name: Lint
        run: pnpm nx affected -t lint
      
      - name: Test
        run: pnpm nx affected -t test

      - name: Build  
        run: pnpm nx affected -t build

  build-finished:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Trace
        run: echo "All jobs finished successfully"
